# Generated by Django 4.1 on 2025-11-08 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('hod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='MentorMentee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=8)),
                ('userType', models.CharField(default='faculty', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='MentorMentee.department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='MentorMentee.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('topics_discussed', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='MentorMentee.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='MentorMentee.student')),
            ],
        ),
        migrations.CreateModel(
            name='MentorAssignmentLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MentorMentee.admin')),
                ('new_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to='MentorMentee.faculty')),
                ('old_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assignments', to='MentorMentee.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.student')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.login'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MentorMentee.department'),
        ),
        migrations.AddField(
            model_name='admin',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.login'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
