# Generated by Django 4.1 on 2025-11-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
    ]
