# Generated by Django 5.2.8 on 2025-11-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0002_remove_admin_user_remove_faculty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
