# Generated by Django 5.2.8 on 2025-11-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0004_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
