# Generated by Django 5.2.8 on 2025-11-24 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0007_remove_student_created_at_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(blank=True, max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.courses')),
            ],
        ),
    ]
