# Generated by Django 5.2.8 on 2025-11-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0008_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default='2025', on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.batches'),
            preserve_default=False,
        ),
    ]
