# Generated by Django 5.2.8 on 2025-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0009_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
