# Generated by Django 5.2.8 on 2025-11-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0010_student_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='created_at',
        ),
    ]
