# Generated by Django 5.2.8 on 2025-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0011_remove_faculty_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
