# Generated by Django 5.2.8 on 2025-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0012_faculty_faculty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
