# Generated by Django 5.1.7 on 2025-11-26 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0013_admin_admin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringsession',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='application_forms/'),
        ),
        migrations.AddField(
            model_name='student',
            name='assessment_file',
            field=models.FileField(blank=True, null=True, upload_to='assessments/'),
        ),
    ]
