# Generated by Django 5.2.8 on 2025-11-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0013_admin_admin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='assessment_form',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
