# Generated by Django 5.1.7 on 2025-11-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0014_mentoringsession_date_mentoringsession_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringsession',
            name='session_date',
        ),
    ]
