# Generated by Django 5.1.7 on 2025-11-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0015_remove_mentoringsession_session_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringsession',
            name='action_plan',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='mentoringsession',
            name='topics_discussed',
        ),
    ]
