# Generated by Django 5.1.7 on 2025-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0016_remove_mentoringsession_action_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoringsession',
            old_name='summary',
            new_name='academic_details',
        ),
        migrations.AddField(
            model_name='mentoringsession',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
