# Generated by Django 5.2.8 on 2025-12-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0017_rename_summary_mentoringsession_academic_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_images/'),
        ),
    ]
