# Generated by Django 5.2.8 on 2025-11-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0017_rename_summary_mentoringsession_academic_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.login'),
        ),
    ]
