# Generated by Django 5.2.8 on 2025-11-29 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0018_student_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('Cancelled', 'cancelled')], default='Active', max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.batches')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.admin')),
            ],
        ),
    ]
