# Generated by Django 5.2.8 on 2025-12-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0018_alter_faculty_faculty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorassignmentlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MentorMentee.login'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
