# Generated by Django 5.2.8 on 2025-12-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0018_student_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superadmin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('admin_image', models.ImageField(default='default.png', upload_to='superadmin/')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.login')),
            ],
        ),
    ]
