# Generated by Django 5.2.8 on 2025-11-30 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0019_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('cancelled', 'Cancelled')], default='Active', max_length=25),
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='Pending', max_length=25)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_time', models.TimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.student')),
            ],
        ),
    ]
