# Generated by Django 5.2.8 on 2025-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0019_alter_mentorassignmentlog_changed_by_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_admin', True)), fields=('is_admin',), name='only_one_admin_allowed'),
        ),
    ]
