# Generated by Django 5.2.8 on 2025-11-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0020_alter_schedule_status_sessionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
