# Generated by Django 5.2.8 on 2025-12-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0020_faculty_only_one_admin_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_image', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='faculty',
            name='only_one_admin_allowed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='userType',
            field=models.CharField(default='faculty', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorassignmentlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MentorMentee.faculty'),
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MentorMentee.department'),
        ),
        migrations.AddField(
            model_name='admin',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.login'),
        ),
    ]
