# Generated by Django 5.2.8 on 2025-12-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0021_sessionrequest_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUploads',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_file', models.CharField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MentorMentee.student')),
            ],
        ),
    ]
