# Generated by Django 6.0 on 2025-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0022_studentuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuploads',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
