# Generated by Django 6.0 on 2025-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0023_studentuploads_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuploads',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
