# Generated by Django 6.0 on 2025-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0024_studentuploads_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuploads',
            name='upload_file',
            field=models.FileField(upload_to='student_uploads/'),
        ),
    ]
