# Generated by Django 6.0 on 2025-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0025_alter_studentuploads_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuploads',
            name='upload_file',
            field=models.CharField(max_length=500),
        ),
    ]
