# Generated by Django 6.0 on 2025-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0027_alter_studentuploads_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuploads',
            name='upload_file',
            field=models.FileField(max_length=500, upload_to='student_uploads/'),
        ),
    ]
