# Generated by Django 6.0 on 2025-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorMentee', '0028_alter_studentuploads_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='batch_mail',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
